set_property PACKAGE_PIN D18 [get_ports i_uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports i_uart_rx]
set_property PACKAGE_PIN D17 [get_ports o_uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports o_uart_tx]

set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports i_sys_clk_p]
set_property PACKAGE_PIN AD12 [get_ports i_sys_clk_p]
set_property PACKAGE_PIN AD11 [get_ports i_sys_clk_n]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports i_sys_clk_n]
set_property PACKAGE_PIN B27 [get_ports {virtual_led[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[31]}]
set_property PACKAGE_PIN A27 [get_ports {virtual_led[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[30]}]
set_property PACKAGE_PIN A26 [get_ports {virtual_led[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[29]}]
set_property PACKAGE_PIN B25 [get_ports {virtual_led[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[28]}]
set_property PACKAGE_PIN A25 [get_ports {virtual_led[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[27]}]
set_property PACKAGE_PIN B24 [get_ports {virtual_led[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[26]}]
set_property PACKAGE_PIN B23 [get_ports {virtual_led[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[25]}]
set_property PACKAGE_PIN A23 [get_ports {virtual_led[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[24]}]
set_property PACKAGE_PIN E30 [get_ports {virtual_led[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[23]}]
set_property PACKAGE_PIN C30 [get_ports {virtual_led[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[22]}]
set_property PACKAGE_PIN D28 [get_ports {virtual_led[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[21]}]
set_property PACKAGE_PIN E26 [get_ports {virtual_led[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[20]}]
set_property PACKAGE_PIN F25 [get_ports {virtual_led[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[19]}]
set_property PACKAGE_PIN D23 [get_ports {virtual_led[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[18]}]
set_property PACKAGE_PIN F23 [get_ports {virtual_led[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[17]}]
set_property PACKAGE_PIN F12 [get_ports {virtual_led[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[16]}]
set_property PACKAGE_PIN G28 [get_ports {virtual_led[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[15]}]
set_property PACKAGE_PIN E28 [get_ports {virtual_led[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[14]}]
set_property PACKAGE_PIN C29 [get_ports {virtual_led[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[13]}]
set_property PACKAGE_PIN D26 [get_ports {virtual_led[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[12]}]
set_property PACKAGE_PIN C25 [get_ports {virtual_led[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[11]}]
set_property PACKAGE_PIN D24 [get_ports {virtual_led[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[10]}]
set_property PACKAGE_PIN E23 [get_ports {virtual_led[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[9]}]
set_property PACKAGE_PIN G23 [get_ports {virtual_led[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[8]}]
set_property PACKAGE_PIN E29 [get_ports {virtual_led[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[7]}]
set_property PACKAGE_PIN G25 [get_ports {virtual_led[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[6]}]
set_property PACKAGE_PIN F26 [get_ports {virtual_led[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[5]}]
set_property PACKAGE_PIN C26 [get_ports {virtual_led[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[4]}]
set_property PACKAGE_PIN E25 [get_ports {virtual_led[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[3]}]
set_property PACKAGE_PIN C24 [get_ports {virtual_led[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[2]}]
set_property PACKAGE_PIN E24 [get_ports {virtual_led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[1]}]
set_property PACKAGE_PIN G24 [get_ports {virtual_led[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_led[0]}]
set_property PACKAGE_PIN L16 [get_ports {virtual_seg[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[9]}]
set_property PACKAGE_PIN L13 [get_ports {virtual_seg[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[8]}]
set_property PACKAGE_PIN K13 [get_ports {virtual_seg[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[7]}]
set_property PACKAGE_PIN L12 [get_ports {virtual_seg[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[6]}]
set_property PACKAGE_PIN K15 [get_ports {virtual_seg[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[5]}]
set_property PACKAGE_PIN K16 [get_ports {virtual_seg[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[4]}]
set_property PACKAGE_PIN J16 [get_ports {virtual_seg[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[3]}]
set_property PACKAGE_PIN H16 [get_ports {virtual_seg[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[2]}]
set_property PACKAGE_PIN L15 [get_ports {virtual_seg[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[1]}]
set_property PACKAGE_PIN K14 [get_ports {virtual_seg[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[0]}]
set_property PACKAGE_PIN K11 [get_ports {virtual_seg[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[19]}]
set_property PACKAGE_PIN J14 [get_ports {virtual_seg[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[18]}]
set_property PACKAGE_PIN G13 [get_ports {virtual_seg[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[17]}]
set_property PACKAGE_PIN F13 [get_ports {virtual_seg[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[16]}]
set_property PACKAGE_PIN H12 [get_ports {virtual_seg[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[15]}]
set_property PACKAGE_PIN J11 [get_ports {virtual_seg[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[14]}]
set_property PACKAGE_PIN L11 [get_ports {virtual_seg[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[13]}]
set_property PACKAGE_PIN J12 [get_ports {virtual_seg[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[12]}]
set_property PACKAGE_PIN H11 [get_ports {virtual_seg[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[11]}]
set_property PACKAGE_PIN J13 [get_ports {virtual_seg[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[10]}]
set_property PACKAGE_PIN AH26 [get_ports {virtual_seg[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[29]}]
set_property PACKAGE_PIN AF28 [get_ports {virtual_seg[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[28]}]
set_property PACKAGE_PIN AF30 [get_ports {virtual_seg[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[27]}]
set_property PACKAGE_PIN AJ26 [get_ports {virtual_seg[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[26]}]
set_property PACKAGE_PIN AH27 [get_ports {virtual_seg[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[25]}]
set_property PACKAGE_PIN AF26 [get_ports {virtual_seg[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[24]}]
set_property PACKAGE_PIN AC26 [get_ports {virtual_seg[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[23]}]
set_property PACKAGE_PIN AF27 [get_ports {virtual_seg[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[22]}]
set_property PACKAGE_PIN AG27 [get_ports {virtual_seg[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[21]}]
set_property PACKAGE_PIN AG28 [get_ports {virtual_seg[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[20]}]
set_property PACKAGE_PIN AJ28 [get_ports {virtual_seg[39]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[39]}]
set_property PACKAGE_PIN AH30 [get_ports {virtual_seg[38]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[38]}]
set_property PACKAGE_PIN AK29 [get_ports {virtual_seg[37]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[37]}]
set_property PACKAGE_PIN AK28 [get_ports {virtual_seg[36]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[36]}]
set_property PACKAGE_PIN AK30 [get_ports {virtual_seg[35]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[35]}]
set_property PACKAGE_PIN AG30 [get_ports {virtual_seg[34]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[34]}]
set_property PACKAGE_PIN AE30 [get_ports {virtual_seg[33]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[33]}]
set_property PACKAGE_PIN AJ27 [get_ports {virtual_seg[32]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[32]}]
set_property PACKAGE_PIN AJ29 [get_ports {virtual_seg[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[31]}]
set_property PACKAGE_PIN AK26 [get_ports {virtual_seg[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {virtual_seg[30]}]

set_clock_groups -asynchronous -group [get_clocks clk_out1_pll] -group [get_clocks clk_out2_pll]

# Stale ILA insertion from a previous debug attempt. build_ila_bit.tcl now owns
# debug core creation so this old u_ila_0 block does not conflict with it.
# if {0} {
# create_debug_core u_ila_0 ila
# set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
# set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
# set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
# set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
# set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
# set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_0]
# set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
# set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
# set_property port_width 1 [get_debug_ports u_ila_0/clk]
# connect_debug_port u_ila_0/clk [get_nets [list pll_inst/inst/clk_out2]]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
# set_property port_width 32 [get_debug_ports u_ila_0/probe0]
# connect_debug_port u_ila_0/probe0 [get_nets [list {student_top_inst/Core_cpu/csr_mcause[0]} {student_top_inst/Core_cpu/csr_mcause[1]} {student_top_inst/Core_cpu/csr_mcause[2]} {student_top_inst/Core_cpu/csr_mcause[3]} {student_top_inst/Core_cpu/csr_mcause[4]} {student_top_inst/Core_cpu/csr_mcause[5]} {student_top_inst/Core_cpu/csr_mcause[6]} {student_top_inst/Core_cpu/csr_mcause[7]} {student_top_inst/Core_cpu/csr_mcause[8]} {student_top_inst/Core_cpu/csr_mcause[9]} {student_top_inst/Core_cpu/csr_mcause[10]} {student_top_inst/Core_cpu/csr_mcause[11]} {student_top_inst/Core_cpu/csr_mcause[12]} {student_top_inst/Core_cpu/csr_mcause[13]} {student_top_inst/Core_cpu/csr_mcause[14]} {student_top_inst/Core_cpu/csr_mcause[15]} {student_top_inst/Core_cpu/csr_mcause[16]} {student_top_inst/Core_cpu/csr_mcause[17]} {student_top_inst/Core_cpu/csr_mcause[18]} {student_top_inst/Core_cpu/csr_mcause[19]} {student_top_inst/Core_cpu/csr_mcause[20]} {student_top_inst/Core_cpu/csr_mcause[21]} {student_top_inst/Core_cpu/csr_mcause[22]} {student_top_inst/Core_cpu/csr_mcause[23]} {student_top_inst/Core_cpu/csr_mcause[24]} {student_top_inst/Core_cpu/csr_mcause[25]} {student_top_inst/Core_cpu/csr_mcause[26]} {student_top_inst/Core_cpu/csr_mcause[27]} {student_top_inst/Core_cpu/csr_mcause[28]} {student_top_inst/Core_cpu/csr_mcause[29]} {student_top_inst/Core_cpu/csr_mcause[30]} {student_top_inst/Core_cpu/csr_mcause[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
# set_property port_width 32 [get_debug_ports u_ila_0/probe1]
# connect_debug_port u_ila_0/probe1 [get_nets [list {student_top_inst/Core_cpu/csr_mstatus[0]} {student_top_inst/Core_cpu/csr_mstatus[1]} {student_top_inst/Core_cpu/csr_mstatus[2]} {student_top_inst/Core_cpu/csr_mstatus[3]} {student_top_inst/Core_cpu/csr_mstatus[4]} {student_top_inst/Core_cpu/csr_mstatus[5]} {student_top_inst/Core_cpu/csr_mstatus[6]} {student_top_inst/Core_cpu/csr_mstatus[7]} {student_top_inst/Core_cpu/csr_mstatus[8]} {student_top_inst/Core_cpu/csr_mstatus[9]} {student_top_inst/Core_cpu/csr_mstatus[10]} {student_top_inst/Core_cpu/csr_mstatus[11]} {student_top_inst/Core_cpu/csr_mstatus[12]} {student_top_inst/Core_cpu/csr_mstatus[13]} {student_top_inst/Core_cpu/csr_mstatus[14]} {student_top_inst/Core_cpu/csr_mstatus[15]} {student_top_inst/Core_cpu/csr_mstatus[16]} {student_top_inst/Core_cpu/csr_mstatus[17]} {student_top_inst/Core_cpu/csr_mstatus[18]} {student_top_inst/Core_cpu/csr_mstatus[19]} {student_top_inst/Core_cpu/csr_mstatus[20]} {student_top_inst/Core_cpu/csr_mstatus[21]} {student_top_inst/Core_cpu/csr_mstatus[22]} {student_top_inst/Core_cpu/csr_mstatus[23]} {student_top_inst/Core_cpu/csr_mstatus[24]} {student_top_inst/Core_cpu/csr_mstatus[25]} {student_top_inst/Core_cpu/csr_mstatus[26]} {student_top_inst/Core_cpu/csr_mstatus[27]} {student_top_inst/Core_cpu/csr_mstatus[28]} {student_top_inst/Core_cpu/csr_mstatus[29]} {student_top_inst/Core_cpu/csr_mstatus[30]} {student_top_inst/Core_cpu/csr_mstatus[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
# set_property port_width 32 [get_debug_ports u_ila_0/probe2]
# connect_debug_port u_ila_0/probe2 [get_nets [list {student_top_inst/Core_cpu/csr_mepc[0]} {student_top_inst/Core_cpu/csr_mepc[1]} {student_top_inst/Core_cpu/csr_mepc[2]} {student_top_inst/Core_cpu/csr_mepc[3]} {student_top_inst/Core_cpu/csr_mepc[4]} {student_top_inst/Core_cpu/csr_mepc[5]} {student_top_inst/Core_cpu/csr_mepc[6]} {student_top_inst/Core_cpu/csr_mepc[7]} {student_top_inst/Core_cpu/csr_mepc[8]} {student_top_inst/Core_cpu/csr_mepc[9]} {student_top_inst/Core_cpu/csr_mepc[10]} {student_top_inst/Core_cpu/csr_mepc[11]} {student_top_inst/Core_cpu/csr_mepc[12]} {student_top_inst/Core_cpu/csr_mepc[13]} {student_top_inst/Core_cpu/csr_mepc[14]} {student_top_inst/Core_cpu/csr_mepc[15]} {student_top_inst/Core_cpu/csr_mepc[16]} {student_top_inst/Core_cpu/csr_mepc[17]} {student_top_inst/Core_cpu/csr_mepc[18]} {student_top_inst/Core_cpu/csr_mepc[19]} {student_top_inst/Core_cpu/csr_mepc[20]} {student_top_inst/Core_cpu/csr_mepc[21]} {student_top_inst/Core_cpu/csr_mepc[22]} {student_top_inst/Core_cpu/csr_mepc[23]} {student_top_inst/Core_cpu/csr_mepc[24]} {student_top_inst/Core_cpu/csr_mepc[25]} {student_top_inst/Core_cpu/csr_mepc[26]} {student_top_inst/Core_cpu/csr_mepc[27]} {student_top_inst/Core_cpu/csr_mepc[28]} {student_top_inst/Core_cpu/csr_mepc[29]} {student_top_inst/Core_cpu/csr_mepc[30]} {student_top_inst/Core_cpu/csr_mepc[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
# set_property port_width 32 [get_debug_ports u_ila_0/probe3]
# connect_debug_port u_ila_0/probe3 [get_nets [list {student_top_inst/Core_cpu/csr_mtvec[0]} {student_top_inst/Core_cpu/csr_mtvec[1]} {student_top_inst/Core_cpu/csr_mtvec[2]} {student_top_inst/Core_cpu/csr_mtvec[3]} {student_top_inst/Core_cpu/csr_mtvec[4]} {student_top_inst/Core_cpu/csr_mtvec[5]} {student_top_inst/Core_cpu/csr_mtvec[6]} {student_top_inst/Core_cpu/csr_mtvec[7]} {student_top_inst/Core_cpu/csr_mtvec[8]} {student_top_inst/Core_cpu/csr_mtvec[9]} {student_top_inst/Core_cpu/csr_mtvec[10]} {student_top_inst/Core_cpu/csr_mtvec[11]} {student_top_inst/Core_cpu/csr_mtvec[12]} {student_top_inst/Core_cpu/csr_mtvec[13]} {student_top_inst/Core_cpu/csr_mtvec[14]} {student_top_inst/Core_cpu/csr_mtvec[15]} {student_top_inst/Core_cpu/csr_mtvec[16]} {student_top_inst/Core_cpu/csr_mtvec[17]} {student_top_inst/Core_cpu/csr_mtvec[18]} {student_top_inst/Core_cpu/csr_mtvec[19]} {student_top_inst/Core_cpu/csr_mtvec[20]} {student_top_inst/Core_cpu/csr_mtvec[21]} {student_top_inst/Core_cpu/csr_mtvec[22]} {student_top_inst/Core_cpu/csr_mtvec[23]} {student_top_inst/Core_cpu/csr_mtvec[24]} {student_top_inst/Core_cpu/csr_mtvec[25]} {student_top_inst/Core_cpu/csr_mtvec[26]} {student_top_inst/Core_cpu/csr_mtvec[27]} {student_top_inst/Core_cpu/csr_mtvec[28]} {student_top_inst/Core_cpu/csr_mtvec[29]} {student_top_inst/Core_cpu/csr_mtvec[30]} {student_top_inst/Core_cpu/csr_mtvec[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
# set_property port_width 32 [get_debug_ports u_ila_0/probe4]
# connect_debug_port u_ila_0/probe4 [get_nets [list {student_top_inst/Core_cpu/exmem_alu_y[0]} {student_top_inst/Core_cpu/exmem_alu_y[1]} {student_top_inst/Core_cpu/exmem_alu_y[2]} {student_top_inst/Core_cpu/exmem_alu_y[3]} {student_top_inst/Core_cpu/exmem_alu_y[4]} {student_top_inst/Core_cpu/exmem_alu_y[5]} {student_top_inst/Core_cpu/exmem_alu_y[6]} {student_top_inst/Core_cpu/exmem_alu_y[7]} {student_top_inst/Core_cpu/exmem_alu_y[8]} {student_top_inst/Core_cpu/exmem_alu_y[9]} {student_top_inst/Core_cpu/exmem_alu_y[10]} {student_top_inst/Core_cpu/exmem_alu_y[11]} {student_top_inst/Core_cpu/exmem_alu_y[12]} {student_top_inst/Core_cpu/exmem_alu_y[13]} {student_top_inst/Core_cpu/exmem_alu_y[14]} {student_top_inst/Core_cpu/exmem_alu_y[15]} {student_top_inst/Core_cpu/exmem_alu_y[16]} {student_top_inst/Core_cpu/exmem_alu_y[17]} {student_top_inst/Core_cpu/exmem_alu_y[18]} {student_top_inst/Core_cpu/exmem_alu_y[19]} {student_top_inst/Core_cpu/exmem_alu_y[20]} {student_top_inst/Core_cpu/exmem_alu_y[21]} {student_top_inst/Core_cpu/exmem_alu_y[22]} {student_top_inst/Core_cpu/exmem_alu_y[23]} {student_top_inst/Core_cpu/exmem_alu_y[24]} {student_top_inst/Core_cpu/exmem_alu_y[25]} {student_top_inst/Core_cpu/exmem_alu_y[26]} {student_top_inst/Core_cpu/exmem_alu_y[27]} {student_top_inst/Core_cpu/exmem_alu_y[28]} {student_top_inst/Core_cpu/exmem_alu_y[29]} {student_top_inst/Core_cpu/exmem_alu_y[30]} {student_top_inst/Core_cpu/exmem_alu_y[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
# set_property port_width 2 [get_debug_ports u_ila_0/probe5]
# connect_debug_port u_ila_0/probe5 [get_nets [list {student_top_inst/Core_cpu/exmem_mem_mask[0]} {student_top_inst/Core_cpu/exmem_mem_mask[1]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
# set_property port_width 32 [get_debug_ports u_ila_0/probe6]
# connect_debug_port u_ila_0/probe6 [get_nets [list {student_top_inst/Core_cpu/id_mul_helper_ra[0]} {student_top_inst/Core_cpu/id_mul_helper_ra[1]} {student_top_inst/Core_cpu/id_mul_helper_ra[2]} {student_top_inst/Core_cpu/id_mul_helper_ra[3]} {student_top_inst/Core_cpu/id_mul_helper_ra[4]} {student_top_inst/Core_cpu/id_mul_helper_ra[5]} {student_top_inst/Core_cpu/id_mul_helper_ra[6]} {student_top_inst/Core_cpu/id_mul_helper_ra[7]} {student_top_inst/Core_cpu/id_mul_helper_ra[8]} {student_top_inst/Core_cpu/id_mul_helper_ra[9]} {student_top_inst/Core_cpu/id_mul_helper_ra[10]} {student_top_inst/Core_cpu/id_mul_helper_ra[11]} {student_top_inst/Core_cpu/id_mul_helper_ra[12]} {student_top_inst/Core_cpu/id_mul_helper_ra[13]} {student_top_inst/Core_cpu/id_mul_helper_ra[14]} {student_top_inst/Core_cpu/id_mul_helper_ra[15]} {student_top_inst/Core_cpu/id_mul_helper_ra[16]} {student_top_inst/Core_cpu/id_mul_helper_ra[17]} {student_top_inst/Core_cpu/id_mul_helper_ra[18]} {student_top_inst/Core_cpu/id_mul_helper_ra[19]} {student_top_inst/Core_cpu/id_mul_helper_ra[20]} {student_top_inst/Core_cpu/id_mul_helper_ra[21]} {student_top_inst/Core_cpu/id_mul_helper_ra[22]} {student_top_inst/Core_cpu/id_mul_helper_ra[23]} {student_top_inst/Core_cpu/id_mul_helper_ra[24]} {student_top_inst/Core_cpu/id_mul_helper_ra[25]} {student_top_inst/Core_cpu/id_mul_helper_ra[26]} {student_top_inst/Core_cpu/id_mul_helper_ra[27]} {student_top_inst/Core_cpu/id_mul_helper_ra[28]} {student_top_inst/Core_cpu/id_mul_helper_ra[29]} {student_top_inst/Core_cpu/id_mul_helper_ra[30]} {student_top_inst/Core_cpu/id_mul_helper_ra[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
# set_property port_width 3 [get_debug_ports u_ila_0/probe7]
# connect_debug_port u_ila_0/probe7 [get_nets [list {student_top_inst/Core_cpu/exmem_funct3[0]} {student_top_inst/Core_cpu/exmem_funct3[1]} {student_top_inst/Core_cpu/exmem_funct3[2]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
# set_property port_width 32 [get_debug_ports u_ila_0/probe8]
# connect_debug_port u_ila_0/probe8 [get_nets [list {student_top_inst/Core_cpu/ex_pc_target[0]} {student_top_inst/Core_cpu/ex_pc_target[1]} {student_top_inst/Core_cpu/ex_pc_target[2]} {student_top_inst/Core_cpu/ex_pc_target[3]} {student_top_inst/Core_cpu/ex_pc_target[4]} {student_top_inst/Core_cpu/ex_pc_target[5]} {student_top_inst/Core_cpu/ex_pc_target[6]} {student_top_inst/Core_cpu/ex_pc_target[7]} {student_top_inst/Core_cpu/ex_pc_target[8]} {student_top_inst/Core_cpu/ex_pc_target[9]} {student_top_inst/Core_cpu/ex_pc_target[10]} {student_top_inst/Core_cpu/ex_pc_target[11]} {student_top_inst/Core_cpu/ex_pc_target[12]} {student_top_inst/Core_cpu/ex_pc_target[13]} {student_top_inst/Core_cpu/ex_pc_target[14]} {student_top_inst/Core_cpu/ex_pc_target[15]} {student_top_inst/Core_cpu/ex_pc_target[16]} {student_top_inst/Core_cpu/ex_pc_target[17]} {student_top_inst/Core_cpu/ex_pc_target[18]} {student_top_inst/Core_cpu/ex_pc_target[19]} {student_top_inst/Core_cpu/ex_pc_target[20]} {student_top_inst/Core_cpu/ex_pc_target[21]} {student_top_inst/Core_cpu/ex_pc_target[22]} {student_top_inst/Core_cpu/ex_pc_target[23]} {student_top_inst/Core_cpu/ex_pc_target[24]} {student_top_inst/Core_cpu/ex_pc_target[25]} {student_top_inst/Core_cpu/ex_pc_target[26]} {student_top_inst/Core_cpu/ex_pc_target[27]} {student_top_inst/Core_cpu/ex_pc_target[28]} {student_top_inst/Core_cpu/ex_pc_target[29]} {student_top_inst/Core_cpu/ex_pc_target[30]} {student_top_inst/Core_cpu/ex_pc_target[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
# set_property port_width 32 [get_debug_ports u_ila_0/probe9]
# connect_debug_port u_ila_0/probe9 [get_nets [list {student_top_inst/Core_cpu/exmem_store_data[0]} {student_top_inst/Core_cpu/exmem_store_data[1]} {student_top_inst/Core_cpu/exmem_store_data[2]} {student_top_inst/Core_cpu/exmem_store_data[3]} {student_top_inst/Core_cpu/exmem_store_data[4]} {student_top_inst/Core_cpu/exmem_store_data[5]} {student_top_inst/Core_cpu/exmem_store_data[6]} {student_top_inst/Core_cpu/exmem_store_data[7]} {student_top_inst/Core_cpu/exmem_store_data[8]} {student_top_inst/Core_cpu/exmem_store_data[9]} {student_top_inst/Core_cpu/exmem_store_data[10]} {student_top_inst/Core_cpu/exmem_store_data[11]} {student_top_inst/Core_cpu/exmem_store_data[12]} {student_top_inst/Core_cpu/exmem_store_data[13]} {student_top_inst/Core_cpu/exmem_store_data[14]} {student_top_inst/Core_cpu/exmem_store_data[15]} {student_top_inst/Core_cpu/exmem_store_data[16]} {student_top_inst/Core_cpu/exmem_store_data[17]} {student_top_inst/Core_cpu/exmem_store_data[18]} {student_top_inst/Core_cpu/exmem_store_data[19]} {student_top_inst/Core_cpu/exmem_store_data[20]} {student_top_inst/Core_cpu/exmem_store_data[21]} {student_top_inst/Core_cpu/exmem_store_data[22]} {student_top_inst/Core_cpu/exmem_store_data[23]} {student_top_inst/Core_cpu/exmem_store_data[24]} {student_top_inst/Core_cpu/exmem_store_data[25]} {student_top_inst/Core_cpu/exmem_store_data[26]} {student_top_inst/Core_cpu/exmem_store_data[27]} {student_top_inst/Core_cpu/exmem_store_data[28]} {student_top_inst/Core_cpu/exmem_store_data[29]} {student_top_inst/Core_cpu/exmem_store_data[30]} {student_top_inst/Core_cpu/exmem_store_data[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
# set_property port_width 32 [get_debug_ports u_ila_0/probe10]
# connect_debug_port u_ila_0/probe10 [get_nets [list {student_top_inst/Core_cpu/exmem_pc[0]} {student_top_inst/Core_cpu/exmem_pc[1]} {student_top_inst/Core_cpu/exmem_pc[2]} {student_top_inst/Core_cpu/exmem_pc[3]} {student_top_inst/Core_cpu/exmem_pc[4]} {student_top_inst/Core_cpu/exmem_pc[5]} {student_top_inst/Core_cpu/exmem_pc[6]} {student_top_inst/Core_cpu/exmem_pc[7]} {student_top_inst/Core_cpu/exmem_pc[8]} {student_top_inst/Core_cpu/exmem_pc[9]} {student_top_inst/Core_cpu/exmem_pc[10]} {student_top_inst/Core_cpu/exmem_pc[11]} {student_top_inst/Core_cpu/exmem_pc[12]} {student_top_inst/Core_cpu/exmem_pc[13]} {student_top_inst/Core_cpu/exmem_pc[14]} {student_top_inst/Core_cpu/exmem_pc[15]} {student_top_inst/Core_cpu/exmem_pc[16]} {student_top_inst/Core_cpu/exmem_pc[17]} {student_top_inst/Core_cpu/exmem_pc[18]} {student_top_inst/Core_cpu/exmem_pc[19]} {student_top_inst/Core_cpu/exmem_pc[20]} {student_top_inst/Core_cpu/exmem_pc[21]} {student_top_inst/Core_cpu/exmem_pc[22]} {student_top_inst/Core_cpu/exmem_pc[23]} {student_top_inst/Core_cpu/exmem_pc[24]} {student_top_inst/Core_cpu/exmem_pc[25]} {student_top_inst/Core_cpu/exmem_pc[26]} {student_top_inst/Core_cpu/exmem_pc[27]} {student_top_inst/Core_cpu/exmem_pc[28]} {student_top_inst/Core_cpu/exmem_pc[29]} {student_top_inst/Core_cpu/exmem_pc[30]} {student_top_inst/Core_cpu/exmem_pc[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
# set_property port_width 32 [get_debug_ports u_ila_0/probe11]
# connect_debug_port u_ila_0/probe11 [get_nets [list {student_top_inst/Core_cpu/ex_trap_target[0]} {student_top_inst/Core_cpu/ex_trap_target[1]} {student_top_inst/Core_cpu/ex_trap_target[2]} {student_top_inst/Core_cpu/ex_trap_target[3]} {student_top_inst/Core_cpu/ex_trap_target[4]} {student_top_inst/Core_cpu/ex_trap_target[5]} {student_top_inst/Core_cpu/ex_trap_target[6]} {student_top_inst/Core_cpu/ex_trap_target[7]} {student_top_inst/Core_cpu/ex_trap_target[8]} {student_top_inst/Core_cpu/ex_trap_target[9]} {student_top_inst/Core_cpu/ex_trap_target[10]} {student_top_inst/Core_cpu/ex_trap_target[11]} {student_top_inst/Core_cpu/ex_trap_target[12]} {student_top_inst/Core_cpu/ex_trap_target[13]} {student_top_inst/Core_cpu/ex_trap_target[14]} {student_top_inst/Core_cpu/ex_trap_target[15]} {student_top_inst/Core_cpu/ex_trap_target[16]} {student_top_inst/Core_cpu/ex_trap_target[17]} {student_top_inst/Core_cpu/ex_trap_target[18]} {student_top_inst/Core_cpu/ex_trap_target[19]} {student_top_inst/Core_cpu/ex_trap_target[20]} {student_top_inst/Core_cpu/ex_trap_target[21]} {student_top_inst/Core_cpu/ex_trap_target[22]} {student_top_inst/Core_cpu/ex_trap_target[23]} {student_top_inst/Core_cpu/ex_trap_target[24]} {student_top_inst/Core_cpu/ex_trap_target[25]} {student_top_inst/Core_cpu/ex_trap_target[26]} {student_top_inst/Core_cpu/ex_trap_target[27]} {student_top_inst/Core_cpu/ex_trap_target[28]} {student_top_inst/Core_cpu/ex_trap_target[29]} {student_top_inst/Core_cpu/ex_trap_target[30]} {student_top_inst/Core_cpu/ex_trap_target[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
# set_property port_width 32 [get_debug_ports u_ila_0/probe12]
# connect_debug_port u_ila_0/probe12 [get_nets [list {student_top_inst/Core_cpu/idex_pc[0]} {student_top_inst/Core_cpu/idex_pc[1]} {student_top_inst/Core_cpu/idex_pc[2]} {student_top_inst/Core_cpu/idex_pc[3]} {student_top_inst/Core_cpu/idex_pc[4]} {student_top_inst/Core_cpu/idex_pc[5]} {student_top_inst/Core_cpu/idex_pc[6]} {student_top_inst/Core_cpu/idex_pc[7]} {student_top_inst/Core_cpu/idex_pc[8]} {student_top_inst/Core_cpu/idex_pc[9]} {student_top_inst/Core_cpu/idex_pc[10]} {student_top_inst/Core_cpu/idex_pc[11]} {student_top_inst/Core_cpu/idex_pc[12]} {student_top_inst/Core_cpu/idex_pc[13]} {student_top_inst/Core_cpu/idex_pc[14]} {student_top_inst/Core_cpu/idex_pc[15]} {student_top_inst/Core_cpu/idex_pc[16]} {student_top_inst/Core_cpu/idex_pc[17]} {student_top_inst/Core_cpu/idex_pc[18]} {student_top_inst/Core_cpu/idex_pc[19]} {student_top_inst/Core_cpu/idex_pc[20]} {student_top_inst/Core_cpu/idex_pc[21]} {student_top_inst/Core_cpu/idex_pc[22]} {student_top_inst/Core_cpu/idex_pc[23]} {student_top_inst/Core_cpu/idex_pc[24]} {student_top_inst/Core_cpu/idex_pc[25]} {student_top_inst/Core_cpu/idex_pc[26]} {student_top_inst/Core_cpu/idex_pc[27]} {student_top_inst/Core_cpu/idex_pc[28]} {student_top_inst/Core_cpu/idex_pc[29]} {student_top_inst/Core_cpu/idex_pc[30]} {student_top_inst/Core_cpu/idex_pc[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
# set_property port_width 3 [get_debug_ports u_ila_0/probe13]
# connect_debug_port u_ila_0/probe13 [get_nets [list {student_top_inst/Core_cpu/idex_funct3[0]} {student_top_inst/Core_cpu/idex_funct3[1]} {student_top_inst/Core_cpu/idex_funct3[2]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
# set_property port_width 32 [get_debug_ports u_ila_0/probe14]
# connect_debug_port u_ila_0/probe14 [get_nets [list {student_top_inst/Core_cpu/ifid_instr[0]} {student_top_inst/Core_cpu/ifid_instr[1]} {student_top_inst/Core_cpu/ifid_instr[2]} {student_top_inst/Core_cpu/ifid_instr[3]} {student_top_inst/Core_cpu/ifid_instr[4]} {student_top_inst/Core_cpu/ifid_instr[5]} {student_top_inst/Core_cpu/ifid_instr[6]} {student_top_inst/Core_cpu/ifid_instr[7]} {student_top_inst/Core_cpu/ifid_instr[8]} {student_top_inst/Core_cpu/ifid_instr[9]} {student_top_inst/Core_cpu/ifid_instr[10]} {student_top_inst/Core_cpu/ifid_instr[11]} {student_top_inst/Core_cpu/ifid_instr[12]} {student_top_inst/Core_cpu/ifid_instr[13]} {student_top_inst/Core_cpu/ifid_instr[14]} {student_top_inst/Core_cpu/ifid_instr[15]} {student_top_inst/Core_cpu/ifid_instr[16]} {student_top_inst/Core_cpu/ifid_instr[17]} {student_top_inst/Core_cpu/ifid_instr[18]} {student_top_inst/Core_cpu/ifid_instr[19]} {student_top_inst/Core_cpu/ifid_instr[20]} {student_top_inst/Core_cpu/ifid_instr[21]} {student_top_inst/Core_cpu/ifid_instr[22]} {student_top_inst/Core_cpu/ifid_instr[23]} {student_top_inst/Core_cpu/ifid_instr[24]} {student_top_inst/Core_cpu/ifid_instr[25]} {student_top_inst/Core_cpu/ifid_instr[26]} {student_top_inst/Core_cpu/ifid_instr[27]} {student_top_inst/Core_cpu/ifid_instr[28]} {student_top_inst/Core_cpu/ifid_instr[29]} {student_top_inst/Core_cpu/ifid_instr[30]} {student_top_inst/Core_cpu/ifid_instr[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
# set_property port_width 32 [get_debug_ports u_ila_0/probe15]
# connect_debug_port u_ila_0/probe15 [get_nets [list {student_top_inst/Core_cpu/mem_load_data[0]} {student_top_inst/Core_cpu/mem_load_data[1]} {student_top_inst/Core_cpu/mem_load_data[2]} {student_top_inst/Core_cpu/mem_load_data[3]} {student_top_inst/Core_cpu/mem_load_data[4]} {student_top_inst/Core_cpu/mem_load_data[5]} {student_top_inst/Core_cpu/mem_load_data[6]} {student_top_inst/Core_cpu/mem_load_data[7]} {student_top_inst/Core_cpu/mem_load_data[8]} {student_top_inst/Core_cpu/mem_load_data[9]} {student_top_inst/Core_cpu/mem_load_data[10]} {student_top_inst/Core_cpu/mem_load_data[11]} {student_top_inst/Core_cpu/mem_load_data[12]} {student_top_inst/Core_cpu/mem_load_data[13]} {student_top_inst/Core_cpu/mem_load_data[14]} {student_top_inst/Core_cpu/mem_load_data[15]} {student_top_inst/Core_cpu/mem_load_data[16]} {student_top_inst/Core_cpu/mem_load_data[17]} {student_top_inst/Core_cpu/mem_load_data[18]} {student_top_inst/Core_cpu/mem_load_data[19]} {student_top_inst/Core_cpu/mem_load_data[20]} {student_top_inst/Core_cpu/mem_load_data[21]} {student_top_inst/Core_cpu/mem_load_data[22]} {student_top_inst/Core_cpu/mem_load_data[23]} {student_top_inst/Core_cpu/mem_load_data[24]} {student_top_inst/Core_cpu/mem_load_data[25]} {student_top_inst/Core_cpu/mem_load_data[26]} {student_top_inst/Core_cpu/mem_load_data[27]} {student_top_inst/Core_cpu/mem_load_data[28]} {student_top_inst/Core_cpu/mem_load_data[29]} {student_top_inst/Core_cpu/mem_load_data[30]} {student_top_inst/Core_cpu/mem_load_data[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
# set_property port_width 5 [get_debug_ports u_ila_0/probe16]
# connect_debug_port u_ila_0/probe16 [get_nets [list {student_top_inst/Core_cpu/memwb_rd[0]} {student_top_inst/Core_cpu/memwb_rd[1]} {student_top_inst/Core_cpu/memwb_rd[2]} {student_top_inst/Core_cpu/memwb_rd[3]} {student_top_inst/Core_cpu/memwb_rd[4]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
# set_property port_width 4 [get_debug_ports u_ila_0/probe17]
# connect_debug_port u_ila_0/probe17 [get_nets [list {student_top_inst/Core_cpu/idex_m_op[0]} {student_top_inst/Core_cpu/idex_m_op[1]} {student_top_inst/Core_cpu/idex_m_op[2]} {student_top_inst/Core_cpu/idex_m_op[3]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
# set_property port_width 2 [get_debug_ports u_ila_0/probe18]
# connect_debug_port u_ila_0/probe18 [get_nets [list {student_top_inst/Core_cpu/idex_pc_sel[0]} {student_top_inst/Core_cpu/idex_pc_sel[1]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
# set_property port_width 32 [get_debug_ports u_ila_0/probe19]
# connect_debug_port u_ila_0/probe19 [get_nets [list {student_top_inst/Core_cpu/ifid_pc[0]} {student_top_inst/Core_cpu/ifid_pc[1]} {student_top_inst/Core_cpu/ifid_pc[2]} {student_top_inst/Core_cpu/ifid_pc[3]} {student_top_inst/Core_cpu/ifid_pc[4]} {student_top_inst/Core_cpu/ifid_pc[5]} {student_top_inst/Core_cpu/ifid_pc[6]} {student_top_inst/Core_cpu/ifid_pc[7]} {student_top_inst/Core_cpu/ifid_pc[8]} {student_top_inst/Core_cpu/ifid_pc[9]} {student_top_inst/Core_cpu/ifid_pc[10]} {student_top_inst/Core_cpu/ifid_pc[11]} {student_top_inst/Core_cpu/ifid_pc[12]} {student_top_inst/Core_cpu/ifid_pc[13]} {student_top_inst/Core_cpu/ifid_pc[14]} {student_top_inst/Core_cpu/ifid_pc[15]} {student_top_inst/Core_cpu/ifid_pc[16]} {student_top_inst/Core_cpu/ifid_pc[17]} {student_top_inst/Core_cpu/ifid_pc[18]} {student_top_inst/Core_cpu/ifid_pc[19]} {student_top_inst/Core_cpu/ifid_pc[20]} {student_top_inst/Core_cpu/ifid_pc[21]} {student_top_inst/Core_cpu/ifid_pc[22]} {student_top_inst/Core_cpu/ifid_pc[23]} {student_top_inst/Core_cpu/ifid_pc[24]} {student_top_inst/Core_cpu/ifid_pc[25]} {student_top_inst/Core_cpu/ifid_pc[26]} {student_top_inst/Core_cpu/ifid_pc[27]} {student_top_inst/Core_cpu/ifid_pc[28]} {student_top_inst/Core_cpu/ifid_pc[29]} {student_top_inst/Core_cpu/ifid_pc[30]} {student_top_inst/Core_cpu/ifid_pc[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
# set_property port_width 32 [get_debug_ports u_ila_0/probe20]
# connect_debug_port u_ila_0/probe20 [get_nets [list {student_top_inst/Core_cpu/memwb_pc[0]} {student_top_inst/Core_cpu/memwb_pc[1]} {student_top_inst/Core_cpu/memwb_pc[2]} {student_top_inst/Core_cpu/memwb_pc[3]} {student_top_inst/Core_cpu/memwb_pc[4]} {student_top_inst/Core_cpu/memwb_pc[5]} {student_top_inst/Core_cpu/memwb_pc[6]} {student_top_inst/Core_cpu/memwb_pc[7]} {student_top_inst/Core_cpu/memwb_pc[8]} {student_top_inst/Core_cpu/memwb_pc[9]} {student_top_inst/Core_cpu/memwb_pc[10]} {student_top_inst/Core_cpu/memwb_pc[11]} {student_top_inst/Core_cpu/memwb_pc[12]} {student_top_inst/Core_cpu/memwb_pc[13]} {student_top_inst/Core_cpu/memwb_pc[14]} {student_top_inst/Core_cpu/memwb_pc[15]} {student_top_inst/Core_cpu/memwb_pc[16]} {student_top_inst/Core_cpu/memwb_pc[17]} {student_top_inst/Core_cpu/memwb_pc[18]} {student_top_inst/Core_cpu/memwb_pc[19]} {student_top_inst/Core_cpu/memwb_pc[20]} {student_top_inst/Core_cpu/memwb_pc[21]} {student_top_inst/Core_cpu/memwb_pc[22]} {student_top_inst/Core_cpu/memwb_pc[23]} {student_top_inst/Core_cpu/memwb_pc[24]} {student_top_inst/Core_cpu/memwb_pc[25]} {student_top_inst/Core_cpu/memwb_pc[26]} {student_top_inst/Core_cpu/memwb_pc[27]} {student_top_inst/Core_cpu/memwb_pc[28]} {student_top_inst/Core_cpu/memwb_pc[29]} {student_top_inst/Core_cpu/memwb_pc[30]} {student_top_inst/Core_cpu/memwb_pc[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
# set_property port_width 32 [get_debug_ports u_ila_0/probe21]
# connect_debug_port u_ila_0/probe21 [get_nets [list {student_top_inst/Core_cpu/pc_q[0]} {student_top_inst/Core_cpu/pc_q[1]} {student_top_inst/Core_cpu/pc_q[2]} {student_top_inst/Core_cpu/pc_q[3]} {student_top_inst/Core_cpu/pc_q[4]} {student_top_inst/Core_cpu/pc_q[5]} {student_top_inst/Core_cpu/pc_q[6]} {student_top_inst/Core_cpu/pc_q[7]} {student_top_inst/Core_cpu/pc_q[8]} {student_top_inst/Core_cpu/pc_q[9]} {student_top_inst/Core_cpu/pc_q[10]} {student_top_inst/Core_cpu/pc_q[11]} {student_top_inst/Core_cpu/pc_q[12]} {student_top_inst/Core_cpu/pc_q[13]} {student_top_inst/Core_cpu/pc_q[14]} {student_top_inst/Core_cpu/pc_q[15]} {student_top_inst/Core_cpu/pc_q[16]} {student_top_inst/Core_cpu/pc_q[17]} {student_top_inst/Core_cpu/pc_q[18]} {student_top_inst/Core_cpu/pc_q[19]} {student_top_inst/Core_cpu/pc_q[20]} {student_top_inst/Core_cpu/pc_q[21]} {student_top_inst/Core_cpu/pc_q[22]} {student_top_inst/Core_cpu/pc_q[23]} {student_top_inst/Core_cpu/pc_q[24]} {student_top_inst/Core_cpu/pc_q[25]} {student_top_inst/Core_cpu/pc_q[26]} {student_top_inst/Core_cpu/pc_q[27]} {student_top_inst/Core_cpu/pc_q[28]} {student_top_inst/Core_cpu/pc_q[29]} {student_top_inst/Core_cpu/pc_q[30]} {student_top_inst/Core_cpu/pc_q[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
# set_property port_width 32 [get_debug_ports u_ila_0/probe22]
# connect_debug_port u_ila_0/probe22 [get_nets [list {student_top_inst/Core_cpu/memwb_wdata[0]} {student_top_inst/Core_cpu/memwb_wdata[1]} {student_top_inst/Core_cpu/memwb_wdata[2]} {student_top_inst/Core_cpu/memwb_wdata[3]} {student_top_inst/Core_cpu/memwb_wdata[4]} {student_top_inst/Core_cpu/memwb_wdata[5]} {student_top_inst/Core_cpu/memwb_wdata[6]} {student_top_inst/Core_cpu/memwb_wdata[7]} {student_top_inst/Core_cpu/memwb_wdata[8]} {student_top_inst/Core_cpu/memwb_wdata[9]} {student_top_inst/Core_cpu/memwb_wdata[10]} {student_top_inst/Core_cpu/memwb_wdata[11]} {student_top_inst/Core_cpu/memwb_wdata[12]} {student_top_inst/Core_cpu/memwb_wdata[13]} {student_top_inst/Core_cpu/memwb_wdata[14]} {student_top_inst/Core_cpu/memwb_wdata[15]} {student_top_inst/Core_cpu/memwb_wdata[16]} {student_top_inst/Core_cpu/memwb_wdata[17]} {student_top_inst/Core_cpu/memwb_wdata[18]} {student_top_inst/Core_cpu/memwb_wdata[19]} {student_top_inst/Core_cpu/memwb_wdata[20]} {student_top_inst/Core_cpu/memwb_wdata[21]} {student_top_inst/Core_cpu/memwb_wdata[22]} {student_top_inst/Core_cpu/memwb_wdata[23]} {student_top_inst/Core_cpu/memwb_wdata[24]} {student_top_inst/Core_cpu/memwb_wdata[25]} {student_top_inst/Core_cpu/memwb_wdata[26]} {student_top_inst/Core_cpu/memwb_wdata[27]} {student_top_inst/Core_cpu/memwb_wdata[28]} {student_top_inst/Core_cpu/memwb_wdata[29]} {student_top_inst/Core_cpu/memwb_wdata[30]} {student_top_inst/Core_cpu/memwb_wdata[31]}]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
# set_property port_width 1 [get_debug_ports u_ila_0/probe23]
# connect_debug_port u_ila_0/probe23 [get_nets [list student_top_inst/Core_cpu/div_busy]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
# set_property port_width 1 [get_debug_ports u_ila_0/probe24]
# connect_debug_port u_ila_0/probe24 [get_nets [list student_top_inst/Core_cpu/div_done]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
# set_property port_width 1 [get_debug_ports u_ila_0/probe25]
# connect_debug_port u_ila_0/probe25 [get_nets [list student_top_inst/Core_cpu/ex_br_take]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
# set_property port_width 1 [get_debug_ports u_ila_0/probe26]
# connect_debug_port u_ila_0/probe26 [get_nets [list student_top_inst/Core_cpu/ex_pc_redirect]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
# set_property port_width 1 [get_debug_ports u_ila_0/probe27]
# connect_debug_port u_ila_0/probe27 [get_nets [list student_top_inst/Core_cpu/ex_trap_enter]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
# set_property port_width 1 [get_debug_ports u_ila_0/probe28]
# connect_debug_port u_ila_0/probe28 [get_nets [list student_top_inst/Core_cpu/ex_trap_return]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
# set_property port_width 1 [get_debug_ports u_ila_0/probe29]
# connect_debug_port u_ila_0/probe29 [get_nets [list student_top_inst/Core_cpu/exmem_mem_req]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
# set_property port_width 1 [get_debug_ports u_ila_0/probe30]
# connect_debug_port u_ila_0/probe30 [get_nets [list student_top_inst/Core_cpu/exmem_mem_write]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
# set_property port_width 1 [get_debug_ports u_ila_0/probe31]
# connect_debug_port u_ila_0/probe31 [get_nets [list student_top_inst/Core_cpu/exmem_valid]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
# set_property port_width 1 [get_debug_ports u_ila_0/probe32]
# connect_debug_port u_ila_0/probe32 [get_nets [list student_top_inst/Core_cpu/id_mul_helper_candidate]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
# set_property port_width 1 [get_debug_ports u_ila_0/probe33]
# connect_debug_port u_ila_0/probe33 [get_nets [list student_top_inst/Core_cpu/id_mul_helper_hit]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
# set_property port_width 1 [get_debug_ports u_ila_0/probe34]
# connect_debug_port u_ila_0/probe34 [get_nets [list student_top_inst/Core_cpu/id_mul_helper_return_match]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
# set_property port_width 1 [get_debug_ports u_ila_0/probe35]
# connect_debug_port u_ila_0/probe35 [get_nets [list student_top_inst/Core_cpu/idex_is_ecall]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
# set_property port_width 1 [get_debug_ports u_ila_0/probe36]
# connect_debug_port u_ila_0/probe36 [get_nets [list student_top_inst/Core_cpu/idex_is_m_ext]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
# set_property port_width 1 [get_debug_ports u_ila_0/probe37]
# connect_debug_port u_ila_0/probe37 [get_nets [list student_top_inst/Core_cpu/idex_is_mret]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
# set_property port_width 1 [get_debug_ports u_ila_0/probe38]
# connect_debug_port u_ila_0/probe38 [get_nets [list student_top_inst/Core_cpu/idex_mul_helper]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
# set_property port_width 1 [get_debug_ports u_ila_0/probe39]
# connect_debug_port u_ila_0/probe39 [get_nets [list student_top_inst/Core_cpu/idex_valid]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
# set_property port_width 1 [get_debug_ports u_ila_0/probe40]
# connect_debug_port u_ila_0/probe40 [get_nets [list student_top_inst/Core_cpu/ifid_valid]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
# set_property port_width 1 [get_debug_ports u_ila_0/probe41]
# connect_debug_port u_ila_0/probe41 [get_nets [list student_top_inst/Core_cpu/load_use_hazard]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
# set_property port_width 1 [get_debug_ports u_ila_0/probe42]
# connect_debug_port u_ila_0/probe42 [get_nets [list student_top_inst/Core_cpu/m_inflight]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
# set_property port_width 1 [get_debug_ports u_ila_0/probe43]
# connect_debug_port u_ila_0/probe43 [get_nets [list student_top_inst/Core_cpu/m_result_ready]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
# set_property port_width 1 [get_debug_ports u_ila_0/probe44]
# connect_debug_port u_ila_0/probe44 [get_nets [list student_top_inst/Core_cpu/m_stall]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe45]
# set_property port_width 1 [get_debug_ports u_ila_0/probe45]
# connect_debug_port u_ila_0/probe45 [get_nets [list student_top_inst/Core_cpu/mem_load_stall]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe46]
# set_property port_width 1 [get_debug_ports u_ila_0/probe46]
# connect_debug_port u_ila_0/probe46 [get_nets [list student_top_inst/Core_cpu/memwb_rf_we]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe47]
# set_property port_width 1 [get_debug_ports u_ila_0/probe47]
# connect_debug_port u_ila_0/probe47 [get_nets [list student_top_inst/Core_cpu/memwb_valid]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe48]
# set_property port_width 1 [get_debug_ports u_ila_0/probe48]
# connect_debug_port u_ila_0/probe48 [get_nets [list student_top_inst/Core_cpu/pc_ex_hazard]]
# create_debug_port u_ila_0 probe
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe49]
# set_property port_width 1 [get_debug_ports u_ila_0/probe49]
# connect_debug_port u_ila_0/probe49 [get_nets [list student_top_inst/Core_cpu/pc_mem_hazard]]
# set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
# set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
# set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
# connect_debug_port dbg_hub/clk [get_nets cpu_clk]
# }
