set_property PACKAGE_PIN AD12 [get_ports i_sys_clk_p]
set_property PACKAGE_PIN AD11 [get_ports i_sys_clk_n]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports i_sys_clk_p]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports i_sys_clk_n]
create_clock -period 8.000 -name sys_clk_125m [get_ports i_sys_clk_p]

set_property PACKAGE_PIN D27 [get_ports hdmi_tx_clk_p]
set_property PACKAGE_PIN C27 [get_ports hdmi_tx_clk_n]
set_property PACKAGE_PIN B30 [get_ports {hdmi_tx_data_p[2]}]
set_property PACKAGE_PIN A30 [get_ports {hdmi_tx_data_n[2]}]
set_property PACKAGE_PIN G29 [get_ports {hdmi_tx_data_p[1]}]
set_property PACKAGE_PIN F30 [get_ports {hdmi_tx_data_n[1]}]
set_property PACKAGE_PIN H30 [get_ports {hdmi_tx_data_p[0]}]
set_property PACKAGE_PIN G30 [get_ports {hdmi_tx_data_n[0]}]

set_property IOSTANDARD TMDS_33 [get_ports hdmi_tx_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_tx_clk_n]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_tx_data_p[*]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_tx_data_n[*]}]
